AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing the function.
Resources:
  LF1indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF1_index_photos2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index_copy
      MemorySize: 128
      Timeout: 30
      Role: ''
      Environment:
        Variables:
          REGION: us-east-1
      
  LF2searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF2_search_photos2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search_copy
      MemorySize: 128
      Timeout: 30
      Role: ''
      Environment:
        Variables:
          REGION: us-east-1
